export const TEST_STATUSES = [
  { value: 'not_started', label: '未开始', type: 'default' },
  { value: 'planned', label: '已规划', type: 'info' },
  { value: 'passed', label: '通过', type: 'success' },
  { value: 'failed', label: '失败', type: 'error' },
  { value: 'blocked', label: '阻塞', type: 'warning' },
  { value: 'not_applicable', label: '不适用', type: 'default' },
];

export const COMPLIANCE_SCENARIOS = {
  isa_total_distance: {
    id: 'isa_total_distance', category: '基础路线', name: '有效测试里程',
    objective: '提供足够长的连续道路测试窗口，覆盖稳定识别、提示与驾驶员交互。',
    autoMetric: 'distanceTotal', target: 50_000, unit: 'km', targetLabel: '≥ 50 km',
    routeHint: '优先选择连续、少折返、可安全重复执行的长路线。',
    evidenceHint: '记录车辆版本、地图版本、开始/结束里程与完整日志。',
  },
  isa_urban: {
    id: 'isa_urban', category: '道路环境', name: '城市道路限速',
    objective: '验证建成区、支路和多路口环境中的限速获取与提示。',
    autoMetric: 'urbanDistance', target: 10_000, unit: 'km', targetLabel: '≥ 10 km',
    routeHint: '选择 primary/secondary/tertiary/residential 混合路段。',
    evidenceHint: '标记进入/离开建成区、交叉口后限速保持及遮挡标志。',
  },
  isa_rural: {
    id: 'isa_rural', category: '道路环境', name: '郊区与普通公路',
    objective: '验证非建成区道路、弯道与无连续路灯场景的限速识别。',
    autoMetric: 'ruralDistance', target: 10_000, unit: 'km', targetLabel: '≥ 10 km',
    routeHint: '选择城际主干道和普通双向道路，避免全部为高速。',
    evidenceHint: '记录默认限速规则、解除限速牌与道路类别变化。',
  },
  isa_motorway: {
    id: 'isa_motorway', category: '道路环境', name: '高速/快速道路',
    objective: '验证高速入口、出口、匝道及主线限速变化。',
    autoMetric: 'motorwayDistance', target: 15_000, unit: 'km', targetLabel: '≥ 15 km',
    routeHint: '包含 motorway/trunk 与 link 匝道路段。',
    evidenceHint: '记录汇入主线、离开主线、分流及解除限速位置。',
  },
  isa_speed_tagged: {
    id: 'isa_speed_tagged', category: '限速信息', name: '明确限速覆盖',
    objective: '确保路线包含足够多带明确 OSM maxspeed 数据的道路，便于预先核查。',
    autoMetric: 'speedTaggedDistance', target: 10_000, unit: 'km', targetLabel: '≥ 10 km',
    routeHint: '路线生成后查看“限速数据覆盖”；不足时换区域或人工踏勘。',
    evidenceHint: 'OSM 仅用于路线摸底，实车测试必须以现场标志与适用规则为准。',
  },
  isa_speed_changes: {
    id: 'isa_speed_changes', category: '限速信息', name: '多次限速变化',
    objective: '验证限速上调、下调以及路口/道路类别变化后的系统响应。',
    autoMetric: 'speedChangeCount', target: 8, unit: 'count', targetLabel: '≥ 8 次',
    routeHint: '优先包含多个不同 maxspeed 标签且道路类型变化丰富的路线。',
    evidenceHint: '记录标志位置、系统显示变化点、距离误差和响应时间。',
  },
  isa_speed_diversity: {
    id: 'isa_speed_diversity', category: '限速信息', name: '限速值多样性',
    objective: '覆盖多个不同限速值及特殊限速表达。',
    autoMetric: 'uniqueSpeedLimitCount', target: 4, unit: 'count', targetLabel: '≥ 4 种',
    routeHint: '混合城市、城郊和高速环境通常更容易获得不同限速值。',
    evidenceHint: '记录每种限速值至少一个可复现样本。',
  },
  isa_conditional: {
    id: 'isa_conditional', category: '复杂规则', name: '条件限速',
    objective: '验证按时间、天气、车型等条件生效的限速规则。',
    autoMetric: 'conditionalSpeedDistance', target: 1, unit: 'presence', targetLabel: '至少 1 处',
    routeHint: '查找 maxspeed:conditional 或明确时段/天气条件道路。',
    evidenceHint: '分别在条件生效与不生效时执行，保存时间和天气证据。',
  },
  isa_variable: {
    id: 'isa_variable', category: '复杂规则', name: '可变限速/电子标志',
    objective: '验证龙门架或电子可变限速与地图限速冲突时的策略。',
    autoMetric: 'variableSpeedDistance', target: 1, unit: 'presence', targetLabel: '至少 1 处',
    routeHint: '优先选择带 signals/variable 标记的高速或城市快速路。',
    evidenceHint: '拍摄电子标志显示值，并同步保存 CAN/系统输出时间戳。',
  },
  isa_entry_exit: {
    id: 'isa_entry_exit', category: '复杂规则', name: '出入口与匝道过渡',
    objective: '验证主路、匝道及相邻道路不同限速之间的切换。',
    autoMetric: 'linkDistance', target: 1_000, unit: 'km', targetLabel: '≥ 1 km',
    routeHint: '路线应含 motorway_link/trunk_link/primary_link。',
    evidenceHint: '记录分流点、限速牌位置以及系统切换发生点。',
  },
  isa_school: {
    id: 'isa_school', category: '复杂规则', name: '学校/低速区域',
    objective: '验证学校区域、低速区以及可能带时间条件的限速。',
    autoMetric: 'schoolZoneDistance', target: 1, unit: 'presence', targetLabel: '至少 1 处',
    routeHint: 'OSM 标记稀疏时需结合现场踏勘和当地地图人工确认。',
    evidenceHint: '记录上学时段、补充标牌、道路标线及限速生效条件。',
  },
  isa_roadworks: {
    id: 'isa_roadworks', category: '复杂规则', name: '施工临时限速',
    objective: '验证临时施工标志优先级和短期变化的识别能力。',
    manualOnly: true, targetLabel: '至少 1 处',
    routeHint: '施工场景变化快，应在测试当天踏勘并准备替代路段。',
    evidenceHint: '记录施工标牌、临时车道和导航地图信息是否冲突。',
  },
  isa_unposted: {
    id: 'isa_unposted', category: '复杂规则', name: '无重复标志/默认限速',
    objective: '验证跨路口后无重复标志、建成区默认限速等隐含规则。',
    manualOnly: true, targetLabel: '至少 3 处',
    routeHint: '选择当地默认限速规则典型、标志并不连续重复的道路。',
    evidenceHint: '记录道路入口、行政区边界和系统保持/恢复限速行为。',
  },
  isa_override: {
    id: 'isa_override', category: 'HMI与控制', name: '驾驶员超驰与抑制',
    objective: '验证驾驶员可平顺超驰、系统反馈和每次启动后的状态策略。',
    manualOnly: true, targetLabel: '每种交互至少 3 次',
    routeHint: '仅在安全、合法且有充分道路余量的路段执行。',
    evidenceHint: '记录操作方式、系统反馈、超驰力/加速踏板行为及恢复条件。',
  },
  isa_accuracy: {
    id: 'isa_accuracy', category: 'HMI与控制', name: '限速判定准确性',
    objective: '统计正确、漏检、误检、延迟和错误限速，形成路线级准确率。',
    manualOnly: true, targetLabel: '全路线统计',
    routeHint: '必须建立带时间戳的真值表，不能只依赖 OSM。',
    evidenceHint: '建议同步视频、定位、系统显示、地图限速和人工真值。',
  },
  isa_units: {
    id: 'isa_units', category: '市场本地化', name: '单位与显示本地化',
    objective: '验证 km/h 与 mph、取整、边界值以及仪表/中控显示一致性。',
    manualOnly: true, targetLabel: '覆盖目标市场单位',
    routeHint: '英国、美国等 mph 市场应单独建立路线和配置基线。',
    evidenceHint: '记录现场标志单位、系统显示值和车辆市场配置。',
  },
  isa_default_rules: {
    id: 'isa_default_rules', category: '市场本地化', name: '国家/州默认限速规则',
    objective: '验证无明确数字标志时，系统对道路类别、建成区和辖区默认规则的处理。',
    manualOnly: true, targetLabel: '每类规则至少 3 处',
    routeHint: '在立项时整理目标国家及州/地区的适用规则与例外。',
    evidenceHint: '记录辖区、道路类别、入口标志及所采用的法规真值。',
  },
  isa_sign_variants: {
    id: 'isa_sign_variants', category: '市场本地化', name: '本地标志变体与补充牌',
    objective: '覆盖目标市场的数字限速、区域限速、解除限速及补充条件标牌。',
    manualOnly: true, targetLabel: '建立标志样本集',
    routeHint: '结合当地交通标志规范和实地踏勘建立可复现路线。',
    evidenceHint: '每种标志保留照片、坐标、方向、适用车道和识别结果。',
  },
  isa_cross_jurisdiction: {
    id: 'isa_cross_jurisdiction', category: '市场本地化', name: '跨辖区/边界切换',
    objective: '验证国家、州、省或行政区边界前后默认规则和地图数据切换。',
    manualOnly: true, targetLabel: '至少 1 条跨界路线',
    routeHint: '选择边界附近安全、可重复且规则存在差异的道路。',
    evidenceHint: '记录边界点、地图版本、网络状态和规则切换时间。',
  },
  lane_motorway: {
    id: 'lane_motorway', category: '车道支持', name: '高速车道保持路线',
    objective: '覆盖清晰标线、弯道、出入口和相邻车辆干扰场景。',
    autoMetric: 'motorwayDistance', target: 20_000, unit: 'km', targetLabel: '≥ 20 km',
    routeHint: '选择长距离高速，结合不同曲率与匝道。',
    evidenceHint: '记录标线质量、曲率、车速和系统介入/退出原因。',
  },
  lane_degraded: {
    id: 'lane_degraded', category: '车道支持', name: '弱化/缺失标线',
    objective: '验证磨损、施工、合流和短时缺失标线下的系统边界。',
    manualOnly: true, targetLabel: '至少 5 处',
    routeHint: '需预先人工踏勘，优先选择可安全复测的路段。',
    evidenceHint: '拍摄标线状态并记录退出提示是否及时。',
  },
  aeb_public_context: {
    id: 'aeb_public_context', category: 'AEB环境摸底', name: 'AEB道路环境采集',
    objective: '采集城市、郊区、高速和交叉口背景数据，用于感知与误触发评估。',
    autoMetric: 'distanceTotal', target: 100_000, unit: 'km', targetLabel: '≥ 100 km',
    routeHint: '公共道路只做被动数据采集和误触发观察，不执行碰撞目标试验。',
    evidenceHint: '目标碰撞测试应在封闭场地按适用协议执行。',
  },
  tunnel_transition: {
    id: 'tunnel_transition', category: '环境鲁棒性', name: '隧道明暗切换',
    objective: '验证定位、视觉识别和提示在隧道进出口的连续性。',
    autoMetric: 'tunnelDistance', target: 500, unit: 'km', targetLabel: '≥ 0.5 km',
    routeHint: '优先含多个进出口或长隧道的路线。',
    evidenceHint: '记录光照突变、GNSS状态和系统降级提示。',
  },
  roundabout: {
    id: 'roundabout', category: '道路结构', name: '环岛场景',
    objective: '验证环岛入口、出口和限速继承/变化。',
    autoMetric: 'roundaboutCount', target: 3, unit: 'count', targetLabel: '≥ 3 个',
    routeHint: '欧洲城市与郊区路线优先覆盖不同尺寸环岛。',
    evidenceHint: '记录每个出口后的限速状态和道路识别。',
  },
  night_drive: {
    id: 'night_drive', category: '环境鲁棒性', name: '夜间道路测试',
    objective: '验证反光、眩光、低照度与电子标志条件下的识别。',
    manualOnly: true, targetLabel: '至少 30 km',
    routeHint: '复用白天路线，便于对比同一标志的昼夜表现。',
    evidenceHint: '记录日落时间、天气、照度及摄像头状态。',
  },
  adverse_weather: {
    id: 'adverse_weather', category: '环境鲁棒性', name: '雨雪雾等天气',
    objective: '验证能见度降低、路面反光或附着变化下的系统边界。',
    manualOnly: true, targetLabel: '按可用天气执行',
    routeHint: '准备安全替代路线，不为完成用例进入危险天气。',
    evidenceHint: '记录天气、温度、能见度、雨刷状态与系统降级。',
  },
};

export const COMPLIANCE_PROFILES = [
  {
    id: 'eu_gsr_isa',
    name: '欧盟 GSR · ISA 工程摸底',
    market: '欧盟/EEA',
    type: '法规预验证',
    description: '面向智能速度辅助系统的公共道路工程摸底与问题发现，不替代技术服务机构或型式认证试验。',
    references: [
      { label: 'Regulation (EU) 2019/2144', url: 'https://eur-lex.europa.eu/eli/reg/2019/2144/oj' },
      { label: 'Delegated Regulation (EU) 2021/1958', url: 'https://eur-lex.europa.eu/eli/reg_del/2021/1958/oj' },
    ],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_tagged', 'isa_speed_changes', 'isa_speed_diversity', 'isa_conditional', 'isa_variable', 'isa_entry_exit', 'isa_school', 'isa_roadworks', 'isa_unposted', 'isa_override', 'isa_accuracy', 'night_drive'],
  },
  {
    id: 'euroncap_speed_assist',
    name: 'Euro NCAP · Speed Assist 摸底',
    market: '欧洲',
    type: '消费者测试预评估',
    description: '用于路线级数据采集、限速真值准备和系统表现摸底；具体评分以项目适用年份的官方协议为准。',
    references: [
      { label: 'Euro NCAP Safety Assist Protocols', url: 'https://www.euroncap.com/en/for-engineers/protocols/safety-assist/' },
    ],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_changes', 'isa_speed_diversity', 'isa_conditional', 'isa_variable', 'isa_roadworks', 'isa_unposted', 'isa_accuracy', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'global_isa_localization',
    name: '全球 ISA 本地化道路库',
    market: '德国/法国/意大利/西班牙/英国/美国/中国/日本/韩国/澳大利亚',
    type: '市场适配',
    description: '聚焦不同国家标志体系、默认限速、单位、区域规则和地图数据差异，适合出海前建立各市场基准路线。',
    references: [],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_tagged', 'isa_speed_changes', 'isa_speed_diversity', 'isa_conditional', 'isa_variable', 'isa_entry_exit', 'isa_school', 'isa_roadworks', 'isa_unposted', 'isa_accuracy', 'roundabout', 'tunnel_transition', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'uk_speed_assist',
    name: '英国 ISA/Speed Assist 道路摸底',
    market: '英国',
    type: '市场法规适配',
    description: '聚焦 mph 单位、national speed limit、建成区、可变限速、道路施工和英国标志体系的工程验证。',
    references: [
      { label: 'Traffic Signs Regulations and General Directions 2016', url: 'https://www.legislation.gov.uk/uksi/2016/362/contents' },
      { label: 'UK Highway Code · Speed limits', url: 'https://www.gov.uk/speed-limits' },
    ],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_changes', 'isa_conditional', 'isa_variable', 'isa_roadworks', 'isa_unposted', 'isa_units', 'isa_default_rules', 'isa_sign_variants', 'isa_accuracy', 'roundabout', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'us_speed_assist',
    name: '美国 Speed Assist 道路摸底',
    market: '美国',
    type: '州法规/产品适配',
    description: '面向 MUTCD 标志体系和州级限速差异，覆盖 mph、学校区域、施工区、州界和多车道道路。',
    references: [
      { label: 'FHWA MUTCD 11th Edition', url: 'https://mutcd.fhwa.dot.gov/' },
      { label: 'NHTSA Driver Assistance Technologies', url: 'https://www.nhtsa.gov/vehicle-safety/driver-assistance-technologies' },
    ],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_changes', 'isa_school', 'isa_roadworks', 'isa_units', 'isa_default_rules', 'isa_sign_variants', 'isa_cross_jurisdiction', 'isa_accuracy', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'china_speed_assist',
    name: '中国限速识别/提示道路摸底',
    market: '中国',
    type: '国标/产品适配',
    description: '覆盖城市快速路、高速、普通公路、隧道、施工和复杂附加标志；具体项目需冻结适用 GB/GB/T 与 C-NCAP 版本。',
    references: [
      { label: '国家标准全文公开系统', url: 'https://openstd.samr.gov.cn/' },
      { label: 'C-NCAP 官方网站', url: 'https://www.c-ncap.org.cn/' },
    ],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_changes', 'isa_speed_diversity', 'isa_variable', 'isa_entry_exit', 'isa_school', 'isa_roadworks', 'isa_default_rules', 'isa_sign_variants', 'isa_accuracy', 'tunnel_transition', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'japan_speed_assist',
    name: '日本 Speed Assist 道路摸底',
    market: '日本',
    type: '市场/NCAP适配',
    description: '覆盖城市窄路、一般道路、高速、学校区域、隧道和日本本地标志表达，用于产品本地化验证。',
    references: [
      { label: 'NASVA JNCAP', url: 'https://www.nasva.go.jp/mamoru/en/' },
      { label: 'Japan MLIT Road Bureau', url: 'https://www.mlit.go.jp/road/road_e/index_e.html' },
    ],
    scenarios: ['isa_total_distance', 'isa_urban', 'isa_rural', 'isa_motorway', 'isa_speed_changes', 'isa_school', 'isa_roadworks', 'isa_default_rules', 'isa_sign_variants', 'isa_accuracy', 'tunnel_transition', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'unece_lane_support',
    name: 'UNECE 车道支持道路摸底',
    market: 'UNECE 采用地区',
    type: '法规/性能预验证',
    description: '为车道偏离、车道保持和转向辅助采集不同道路、标线和环境条件，不替代封闭场地法规试验。',
    references: [
      { label: 'UN Regulation No. 79', url: 'https://unece.org/transport/vehicle-regulations-wp29/standards/addenda-1958-agreement-regulations-61-80' },
      { label: 'UN Regulation No. 130', url: 'https://unece.org/transport/vehicle-regulations-wp29/standards/addenda-1958-agreement-regulations-121-140' },
    ],
    scenarios: ['isa_total_distance', 'lane_motorway', 'lane_degraded', 'tunnel_transition', 'night_drive', 'adverse_weather'],
  },
  {
    id: 'unece_aeb_data',
    name: 'UNECE/NCAP AEB 道路数据采集',
    market: '全球主要市场',
    type: '公共道路数据采集',
    description: '用于感知背景、误触发和场景库采集。公共道路禁止主动制造危险或执行碰撞目标试验。',
    references: [
      { label: 'UN Regulation No. 152', url: 'https://unece.org/transport/vehicle-regulations-wp29/standards/addenda-1958-agreement-regulations-141-160' },
    ],
    scenarios: ['aeb_public_context', 'isa_urban', 'isa_rural', 'isa_motorway', 'roundabout', 'tunnel_transition', 'night_drive', 'adverse_weather'],
  },
];

export function getComplianceProfile(profileId) {
  return COMPLIANCE_PROFILES.find(profile => profile.id === profileId) || COMPLIANCE_PROFILES[0];
}
